---
# tasks/CentOS.yml for repo_collabora_code

- name: set fact for task names to Add
  set_fact:
    wtd_repo_collabora_code_task_name: "Add"
  when: wtd_repo_collabora_code_state == "present"

- name: set fact for task names to Remove
  set_fact:
    wtd_repo_collabora_code_task_name: "Remove"
  when: wtd_repo_collabora_code_state != "present"

- name: "{{ wtd_repo_collabora_code_task_name }} key for repository Collabora Online CODE"
  rpm_key:
    state: "{{ wtd_repo_collabora_code_state }}"
    key: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-centos7/repodata/repomd.xml.key
  become: yes

- name: "{{ wtd_repo_collabora_code_task_name }} repository Collabora Online CODE"
  yum_repository:
    name: Collabora Online CODE
    description: Collabora Online CODE
    file: collabora-online-code
    baseurl: "https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-centos7"
    gpgcheck: yes
    gpgkey: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-centos7/repodata/repomd.xml.key
    state: "{{ wtd_repo_collabora_code_state }}"
  become: yes

- name: Activate cleanup handler
  command: "true"
  notify:
    - Cleanup yum metadata
  when: wtd_repo_collabora_code_state != "present"
